
####################################################################################################################
## Given a Lookup_dict for a corpus, this module generates Tech_dict_lookup.dat for each 2.1, 2.2 etc. directories
## File generated by this module will be input of working_debug/All_Resources.py

#sh $HOME_alignment/tech_dict/run_tech-dict.sh $1 $2 Lookup_dict_ai


#####################################################################################################################
# Given a Lookup_transliterated_dict for a corpus, this module generates Tranliterated_words_first_run.dat for each 2.1, 2.2 etc. directories.

filename=$1
i=1
END=`wc -l $1 | awk '{print $1}'`
END=`expr $END + 1`
while [ "$i" -lt $END ]
    do
    python3 $HOME_alignment/Transliteration/generate_transliterated_file_for_every_sentences.py $1 Lookup_transliteration_final_AI_all_eng.txt  "2."$i
    i=`expr $i + 1` 
    done
#####################################################################################################################
