;(load "new_alignment.clp")
;(bind ?*hpath* (str-cat ?*hpath* "/generate_necessary_facts.clp"))
;(load ?*hpath*)
;(load-facts "manual_lwg.dat")
;(load-facts "word_alignment_tmp1.dat")
;(watch activations)
;;(watch rules)
;;(watch facts)
;(run)
;(save-facts "word_alignment_tmp2.dat" local alignment_info)
;(clear)
;====================================================================
(load "new_alignment.clp")
(bind ?*hpath* (str-cat ?*hpath* "/test_stop_Pth_layer_parser_clause_boundary_violations.clp"))
(load ?*hpath*)
(watch activations)
(watch facts)
(load-facts "E_wordid-word_mapping.dat")
(load-facts "revised_preferred_morph.dat")
(load-facts "word_alignment_tmp2.dat")
(load-facts "E_chunk_ids.dat")
(load-facts "H_grouping_template.dat")
;(run)
;====================================================================
