(load "new_alignment.clp")
(bind ?*hpath* (str-cat ?*hpath* "/alignment_clips/check.clp"))
(load ?*hpath*)
(load-facts "E_Group_Facts_Parser_POS.dat")
(load-facts "H_Group_Facts_Parser_POS.dat")
(load-facts "Anchor_Facts.dat")
(run)
(facts)
(save-facts "save_facts1" local final_set-eid-hid)
(save-facts "save_facts2" local proposed_groups)
(save-facts "save_facts_unknown" local anchor_type-english_id-hindi_id)
(exit)

