(load "new_alignment.clp")
(bind ?*hpath* (str-cat ?*hpath* "/working_debug/phrase.clp"))
(load ?*hpath*)
(watch activations)
(load-facts "facts.dat")
;(load-facts "shreya_fact.dat")
(load-facts "H_Group_Facts_Parser_POS.dat")
(load-facts "K_grouping_id_corrected.dat")
(load-facts "K_id_word.dat")
(load-facts "H_wordid-word_mapping.dat")
(load-facts "E_wordid-word_mapping.dat")
(open "Proposed_H_grps_using_dict.dat" debug_v "w")
(watch facts)
(run)
(save-facts "H_grouping_v2.dat" local H_gids)
(save-facts "Phrase2Phrase_Alignment_info.dat" local egids-mfs-hgids)
(clear)
(exit)


