(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/csv_creation/heuristics.clp"))
(load ?*path*)
(load-facts "all_layer_facts.dat")
(load-facts "H_wordid-word_mapping.dat")
(load-facts "cat_consistency_check.dat")
(load-facts "word.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "new_p_layer_tmp.dat" local P1)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/csv_creation/group_kriyA_mUla.clp"))
(load ?*path*)
(load-facts "hindi_meanings_with_grp_ids.dat")
(load-facts "cat_consistency_check.dat")
(load-facts "revised_root.dat")
(load-facts "E_grouping.dat")
(load-facts "H_grouping.dat")
(load-facts "H_wordid-word_mapping.dat")
(load-facts "kriyA_mUla_info.dat")
(load-facts "new_p_layer_tmp.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "E_grouping1.dat" local Eng_label-group_elements)
(save-facts "H_grouping1.dat" local Hnd_label-group_elements)
(save-facts "new_p_layer_tmp1.dat" local P1)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/csv_creation/correct_grouping.clp"))
(load ?*path*)
(load-facts "E_grouping1.dat")
(load-facts "H_grouping1.dat")
(load-facts "all_layer_facts.dat")
(load-facts "hindi_meanings_with_grp_ids.dat")
(load-facts "word.dat")
(load-facts "H_wordid-word_mapping.dat")
(load-facts "new_p_layer_tmp1.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/csv_creation/correct_hindi_grouping.clp"))
(load ?*path*)
(load-facts "wrong_grouping_id.dat")
(load-facts "E_grouping1.dat")
(load-facts "H_grouping1.dat")
;(load-facts "all_layer_facts.dat")
(load-facts "new_p_layer_tmp1.dat")
(load-facts "word.dat")
(load-facts "H_wordid-word_mapping.dat")
(load-facts "eng_wrd_occurence.dat")
(load-facts "hnd_wrd_occurence.dat")
(load-facts "get_all_layer_group_info.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "new_p_layer_tmp2.dat" local P1)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/csv_creation/correct_p_layer.clp"))
(load ?*path*)
(load-facts "parent_sanwawi.dat")
(load-facts "new_p_layer_tmp2.dat")
(load-facts "H_grouping1.dat")
(load-facts "E_grouping1.dat")
(load-facts "H_wordid-word_mapping.dat")
(load-facts "word.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "new_p_layer_tmp3.dat" local P1)
(clear)
(exit)

