(load "/home/roja/Alignment1/csv_creation/correct_grouping.clp")
(load-facts "E_grouping.dat")
(load-facts "H_grouping.dat")
(load-facts "all_layer_facts.dat")
(load-facts "hindi_meanings_with_grp_ids.dat")
(load-facts "word.dat")
(load-facts "H_wordid-word_mapping.dat")
(watch rules)
(watch facts)
(agenda)
;(run)

